const foo1 = a?.b?.c?.d;
const foo2 = a || a.b;
const foo3 = a?.b.c.d;
const foo4 = a?.b.c.d;
const foo5 = a?.b?.c.d;
const foo6 = a?.b && a.d.c.d;
const foo7 = a?.b.c?.d;
const foo8 = a.b?.c;
const foo9 = a.b?.b.b;
const foo10 = a.b?.b.b.b.b;
const foo11 = a?.b.b.b.b.b;
const foo12 = a?.b?.c || a.b.c.d;
const foo13 = a?.[j.k];
const foo14 = a.b?.[c.d];
const foo15 = foo[bar]?.baz;
this.a.b && this.b.c;
